### PR TITLE
Create report_top_N_pop_cities

### PR DESCRIPTION
**Pull request by Nimatumaru**
This report displays top N populated cities in the world, continent, region, country, and district.
kindly review @sousajf1 @mikesobers @Lindon-Jackasal

### CODE REVIEW

**Review by sousajo-cc — CHANGES_REQUESTED** [review]
this is not on markdown format

**Review by Lindon-Jackasal — CHANGES_REQUESTED** [review]
Please number the **Main Success Scenarios** and also the **Extensions**. Also, call this one USE CASE: 7 instead of USE CASE: 3a.

**Comment by Lindon-Jackasal** [comment]
I'm reopening this PR because Nimat needs to update this use case and resubmit so that we can review and merge.

**Review by sousajo-cc — APPROVED** [review]
lgtm

**Review by Lindon-Jackasal — APPROVED** [review]
Looks good. Approve.

**Pull request merged**
