### PR TITLE
Create population.md (Use Case: 8), languages.md (Use Case: 9) & Use Case Diagram

### PR DESCRIPTION
**Pull request by Lindon-Jackasal**
This is use case: 8. It contains the following:
-The population of the world.
-The population of a continent.
-The population of a region.
-The population of a country.
-The population of a district.
-The population of a city.

Please review and provide your feedback.

### CODE REVIEW

**Comment by Lindon-Jackasal** [comment]
I have also added languages.md (Use Case: 9). This use case contains the following:
the number of people who speak the following languages from greatest number to smallest, including the percentage of the world population:
-Chinese
-English
-Hindi
-Spanish
-Arabic

Please review.

**Comment by mikesobers** [comment]
Looks good to me although i am not the expert !! Thank Lindon

**Review by sousajo-cc — APPROVED** [review]
lgtm

**Review by sousajo-cc — APPROVED** [review]
lgtm

**Comment by Lindon-Jackasal** [comment]
Hey guys, I just added the use case diagram. Kindly review and provide your feedback.

**Comment by Nimatumaru** [comment]
well done lindon Thanks.

**Pull request merged**
